# -*- coding: utf-8 -*-
"""Uncertainty Counter

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vuqLkfo2rN8QgxsMHIeHdLTImDalkP2T
"""

!pip install spacy

import spacy
from nltk import tokenize
import nltk
nltk.download('punkt')
import pandas as pd
peacock_words = pd.read_csv("/content/peacock_word_list.csv")
hedge_words = pd.read_csv("/content/hedge_words.csv")
weasel_words = pd.read_csv("/content/weasel_word_list.csv")
weasel_duplicates = pd.read_csv("/content/weasel_duplicate_pos.csv")

nlp = spacy.load("en_core_web_sm")
text = "About thirty people. It's about time. Excellent work by doctors. I would have told you. A few have food. Some apple is looking at buying U.K. startup for $1 billion! Good morning Dr. Adams. The patient is waiting for you in room number 3?"
#text = "many their vision is that trade is in the interest of the many, not the few"
div_sents = tokenize.sent_tokenize(text)

peacock_counter = 0
hedge_full_counter = 0
hedge_lemma_counter = 0
filler_counter = 0
weasel_counter = 0
weasel_dict = dict(zip(weasel_words['lemmas'],weasel_words['pos_tag']))
weasel_dict_dup = dict(zip(weasel_duplicates['lemmas'],weasel_duplicates['pos_tag']))
words = len(text.split())

for sents in div_sents:
  doc = nlp(sents)
  #print(doc)
  for token in doc:
    if token.is_stop == False:
      if peacock_words['lemmas'].str.find(token.lemma_).all()==False:
        peacock_counter += 1
    elif hedge_words['hedges'].str.find(token.text).all()==False:
      hedge_full_counter += 1
    elif hedge_words['fillers'].str.find(token.text).all()==False:
      filler_counter += 1
    elif ((token.lemma_,token.pos_) in weasel_dict.items()) == True:
        print(token.text,token.pos_)
        weasel_counter += 1
    elif ((token.lemma_,token.pos_) in weasel_dict_dup.items()) == True:
        weasel_counter += 1

print("Number of filler words used:",float(filler_counter))
print("Number of weasel words used:",float(weasel_counter))
print("Number of uncertain words:", (float(peacock_counter)+float(hedge_full_counter)+float(weasel_counter)))
print("Total number of words in article:",float(words))
print("Ratio of uncertain to total words:",((float(peacock_counter)+float(hedge_full_counter)+float(weasel_counter))/words)*100)

print(("about","ADV") in weasel_dict.items())

token.text